import { AssessmentItem } from "./assessmentitem.model";
import { AssessmentItemItem } from "./assessmentitemitem.model";
import { Assessment } from "./assessment.model";

export class AssessmentDemo {
  data:Assessment = {"id":'-1',
  "name":"Hand washing demo exam. Click the icon to the right ->",
  "description":"Infection control demo",
  "notes":null,
  "status":"active",
  "comment":'The submit button becomes available when the form is filled out properly',
  "exam_instance_items":[{"id":'48',
  "exam_instance_id":'-1',
  "label":"Hand presentation",
  "description":null,
  "order":0,
  "heading":"1",
  "show_if_id":null,
  "show_if_answer_id":null,
  "exclude_from_total":null,
  "no_comment":null,
  'visible':null,
  'comment':null,
  'selectedvalue':null,
  'selected_id':null,
  'valid':null,
  "items":[{"id":94,"exam_instance_items_id":'48',"label":"S (won't need a comment)","description":"Satisfactory","value":'1',"order":'0',"needscomment":"false"},
  {"id":94,"exam_instance_items_id":'48',"label":"NS (requires a comment)","description":"Not satisfactory","value":'0',"order":'1',"needscomment":"true"}]},
  {"id":'49',"exam_instance_id":'-1',"label":"Adheres to 'bare below the elbow' and no jewellery","description":"Adheres to 'bare below the elbow' and no jewellery","order":1,"heading":null,"show_if_id":null,"show_if_answer_id":null,"exclude_from_total":null,"no_comment":null,
  'visible':null,
  //'comment':null,
  'selectedvalue':null,
  'selected_id':null,
  'valid':null,
  'comment':'Tap here to enter a comment. Label turns green when the item is valid',
  "items":[{"id":95,"exam_instance_items_id":'49',"label":"S (won't need a comment)","description":"Satisfactory","value":'1',"order":'0',"needscomment":"false"},
  {"id":96,"exam_instance_items_id":'49',"label":"NS (requires a comment)","description":"Not satisfactory","value":'0',"order":'1',"needscomment":"true"}]}
  ,{"id":'50',"exam_instance_id":'-1',"label":"Nails are clipped, short, no polish, no false nails","description":"Nails are clipped, short, no polish, no false nails","order":2,"heading":null,"show_if_id":null,"show_if_answer_id":null,"exclude_from_total":null,"no_comment":null,
  'visible':null,
  'comment':'You can have different marking scales if you like',
  'selectedvalue':null,
  'selected_id':null,
  'valid':null,
  "items":[{"id":97,"exam_instance_items_id":'50',"label":"Yes","description":"Satisfactory","value":'1',"order":'0',"needscomment":"false"}
  ,{"id":98,"exam_instance_items_id":'50',"label":"Maybe","description":"Not satisfactory","value":'0',"order":'1',"needscomment":"false"}
  ,{"id":200,"exam_instance_items_id":'50',"label":"No","description":"Not satisfactory","value":'0',"order":'1',"needscomment":"true"}]},
  {"id":'51',"exam_instance_id":'-1',"label":"Water parameters","description":null,"order":3,"heading":"1","show_if_id":null,"show_if_answer_id":null,"exclude_from_total":null,"no_comment":null,
  'visible':null,
  'comment':null,
  'selectedvalue':null,
  'selected_id':null,
  'valid':null,
  "items":[{"id":99,"exam_instance_items_id":'51',"label":"S","description":"Satisfactory","value":'1',"order":'0',"needscomment":"false"},
  {"id":100,"exam_instance_items_id":'51',"label":"NS","description":"Not satisfactory","value":'0',"order":'1',"needscomment":"false"}]},
  {"id":'52',"exam_instance_id":'16',"label":"Tap is turned on with adequate flow of water over hands, not so fast that splashing occurs","description":"Tap is turned on with adequate flow of water over hands, not so fast that splashing occurs","order":4,"heading":null,"show_if_id":null,"show_if_answer_id":null,"exclude_from_total":null,"no_comment":null,
  'visible':null,
  'comment':null,
  'selectedvalue':null,
  'selected_id':null,
  'valid':null,
  "items":[{"id":101,"exam_instance_items_id":'52',"label":"S","description":"Satisfactory","value":'1',"order":'0',"needscomment":"false",},
  {"id":102,"exam_instance_items_id":'52',"label":"NS","description":"Not satisfactory","value":'0',"order":'1',"needscomment":"true"}]},
  {"id":'53',"exam_instance_id":'-1',"label":"Water temperature is comfortable and allows for prolonged rinsing","description":"Water temperature is comfortable and allows for prolonged rinsing","order":5,"heading":null,"show_if_id":null,"show_if_answer_id":null,"exclude_from_total":null,"no_comment":null,
  'visible':null,
  'comment':null,
  'selectedvalue':null,
  'selected_id':null,
  'valid':null,
  "items":[{"id":103,"exam_instance_items_id":'53',"label":"S","description":"Satisfactory","value":'1',"order":'0',"needscomment":"false",},
  {"id":104,"exam_instance_items_id":'53',"label":"NS","description":"Not satisfactory","value":'0',"order":'1',"needscomment":"true"}]},
  {"id":'54',"exam_instance_id":'-1',"label":"Washing technique","description":null,"order":6,"heading":"1","show_if_id":-1,"show_if_answer_id":null,"exclude_from_total":null,"no_comment":null,
  'visible':null,
  'comment':null,
  'selectedvalue':null,
  'selected_id':null,
  'valid':null,
  "items":[]},
  {"id":'55',"exam_instance_id":'-1',"label":"Lathers and scrubs for at least 30 seconds","description":"Lathers and scrubs for at least 30 seconds","order":7,"heading":null,"show_if_id":null,"show_if_answer_id":null,"exclude_from_total":null,"no_comment":null,
  'visible':null,
  'comment':null,
  'selectedvalue':null,
  'selected_id':null,
  'valid':null,
  "items":[{"id":105,"exam_instance_items_id":'55',"label":"S","description":"Satisfactory","value":'1',"order":'0',"needscomment":"false",},
  {"id":106,"exam_instance_items_id":'55',"label":"NS","description":"Not satisfactory","value":'0',"order":'1',"needscomment":"true"}]},
  {"id":'56',"exam_instance_id":'-1',"label":"Overall rating","description":null,"order":8,"heading":"1","show_if_id":-1,"show_if_answer_id":null,"exclude_from_total":null,"no_comment":null,
  'visible':null,
  'comment':null,
  'selectedvalue':null,
  'selected_id':null,
  'valid':null,
  "items":[]},
  {"id":'57',"exam_instance_id":'-1',"label":"Overall rating","description":"Overall rating","order":9,"heading":null,"show_if_id":-1,"show_if_answer_id":null,"exclude_from_total":"1","no_comment":"1",
  'visible':null,
  'comment':null,
  'selectedvalue':null,
  'selected_id':null,
  'valid':null,
  "items":[{"id":107,"exam_instance_items_id":'57',"label":"Satisfactory","description":"Satisfactory","value":'1',"order":'0',"needscomment":"false"},
  {"id":108,"exam_instance_items_id":'57',"label":"Not Satisfactory (opens an additional question)","description":"Not Satisfactory","value":'0',"order":'1',"needscomment":"false"}]},
  {"id":'58',"exam_instance_id":'-1',"label":"Additional Rating","description":"5 point Likert scale for assessor rating","order":10,"heading":null,"show_if_id":57,"show_if_answer_id":107,"exclude_from_total":"1","no_comment":"1",
  'visible':null,
  'comment':null,
  'selectedvalue':null,
  'selected_id':null,
  'valid':null,
  "items":[{"id":109,"exam_instance_items_id":'58',"label":"Strongly disagree","description":"Strongly disagree","value":'0',"order":'0',"needscomment":"false"},
  {"id":110,"exam_instance_items_id":'58',"label":"Disagree","description":"Disagree","value":'1',"order":'1',"needscomment":"false"},
  {"id":111,"exam_instance_items_id":'58',"label":"Neither agree nor disagree","description":"Neither agree nor disagree","value":'2',"order":'2',"needscomment":"false"},
  {"id":112,"exam_instance_items_id":'58',"label":"Agree","description":"Agree","value":'3',"order":'3',"needscomment":"false"},
  {"id":113,"exam_instance_items_id":'58',"label":"Strongly agree","description":"Strongly agree","value":'4',"order":'4',"needscomment":"false"}]}]}
}